### ISSUE TITLE
@ "ValueError: a must be greater than 0" at the cell # Data Setup

### ISSUE THREAD

**Issue by linhduongtuan** [gsurma/histopathologic_cancer_detector#1]
Dear Greg Surma,
Firstly, I thank for your helpful notebook. However, I tried to download your notebook, ran again on my computer and raised an errors at # Data Setup. The error show " - → 7 negatives = dataframe[dataframe.label == 0].sample(SAMPLE_COUNT)" and "ValueError: a must be greater than 0". Could you help me to explain and fix the bug.
Sincerely. Linh
Ps. I try on forked notebook via committing or run it directly each cell that all is fine.

**Comment by gsurma** [comment]
Hi

You're welcome!

I am pretty sure that your issue is caused because the dataset structure you are trying to provide locally is different than on Kaggle.

You should make sure that data in the `training_dir` is like this `['292faf631c5ff5741bb46b04e4eacceb272d8c8b.tif', '5a61b93a34e2a37869a4e83e964169ad3d1e3753.tif', (...)]`.

You can easily check it with the following command `print(os.listdir(training_dir))`.

**Comment by linhduongtuan** [comment]
Dear Greg,
Many thank for your response. I have seen some notebooks listed out the issue and succeeded to fix the bugs. 
All the best for you. 
Linh

**Comment by arief25ramadhan** [comment]
Hi Linhduongtuan, I have a similar problem. Can you tell me how you sorted it out?
Thank you.
Best regards,

Arief Ramadhan
